# Build Android firmware in response to pushed commits to any branch

name: Android Debug CI

on:
  pull_request:
  push:
    branches:
     - 'master'

env:
  DEV_RELEASE_PATH: app/build/outputs/apk/dev/debug/app-dev-debug.apk/*.apk
  PROD_RELEASE_PATH: app/build/outputs/apk/prod/release/app-prod-release.apk/*.apk
  BUILD_NUMBER: ${{ github.run_number }}

jobs:

 instrumentation-test:
   runs-on: macos-latest
   timeout-minutes: 25

   steps:
     - name: Checkout the code
       uses: actions/checkout@v4

     - name: access github
       run: touch github.properties  #Required so that build.gradle works properly

     - name: set up JDK 17
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: 17

     - name: Gradle cache
       uses: gradle/gradle-build-action@v3

     - name: AVD cache
       uses: actions/cache@v4
       id: avd-cache
       with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

     - name: create AVD and generate snapshot for caching
       if: steps.avd-cache.outputs.cache-hit != 'true'
       uses: reactivecircus/android-emulator-runner@v2
       with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

     - name: Run espresso tests
       uses: reactivecircus/android-emulator-runner@v2
       with:
         api-level: 29
         avd-name: test
         force-avd-creation: false
         emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
         disable-animations: true
         script: ./gradlew connectedMockDebugAndroidTest
